aa: rand-m9-mstd0.5-inc1
alpha: 10.0
amp: false
batch_size: 64
beta: 5.0
block: BlockSPTParallel
change_qkv: false
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
cutmix: 0.0
cutmix_minmax: null
data_path: /data/vtab-1k/cifar
data_set: cifar
decay_epochs: 30
decay_rate: 0.1
device: cuda
direct_resize: true
dist_eval: false
dist_url: env://
distributed: false
drop: 0.0
drop_block: null
drop_path: 0.1
epochs: 100
eval: false
exp_name: 20250610_163825-vtab_mae_param_req_0.1_reslora
freeze_kwd: patch_embed
freeze_stage: true
get_sensitivity: false
gp: false
inat_category: name
inception: false
input_size: 224
launcher: none
local_rank: 0
low_rank_dim: 8
lr: 0.001
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_power: 1.0
max_relative_position: 14
min_lr: 1.0e-05
mixup: 0.0
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
mode: super
model: ''
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
model_name: vit_base_patch16_224_in21k_spt
momentum: 0.9
no_abs_pos: false
no_aug: true
no_structured_drop_out: false
no_structured_drop_path: false
num_workers: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: ./saves/cifar_lr-0.001_wd-0.0001
patch_size: 16
patience_epochs: 10
pin_mem: true
platform: pai
post_norm: false
recount: 1
relative_position: false
remode: pixel
repeated_aug: false
reprob: 0.25
resplit: false
resume: checkpoints/mae_pretrain_vit_base.pth
rpe_type: bias
save_best: false
scaler: naive
sched: cosine
seed: 0
sensitivity_batch_num: 16
sensitivity_path: sensitivity_reslora_mae_a10/cifar/param_req_0.1.pth
smoothing: 0.0
start_epoch: 0
structured_only: false
structured_type: lora
structured_vector: true
teacher_model: ''
test: true
train_interpolation: bicubic
val_interval: 10
warmup_epochs: 10
warmup_lr: 1.0e-06
weight_decay: 0.0001
world_size: 1
